#ifndef LSDSLAMTRACKING_GLOBAL_H
#define LSDSLAMTRACKING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LSDSLAMTRACKING_LIBRARY)
#  define LSDSLAMTRACKINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LSDSLAMTRACKINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LSDSLAMTRACKING_GLOBAL_H
